Controllers/ChefController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using ChefsAndDishes.Models;


namespace ChefsAndDishes.Controllers
{
    public class ChefController : Controller
    {
        public ChefController(ChefsAndDishesContext context) { _db = context; }

        [HttpGet("chefs")]
        public IActionResult All()
        {
            List<Chef> Chefs = _db.Chefs.ToList();
            return View("All", Chefs);
        }

        [HttpGet("chefs/new")]
        public IActionResult New()
        {
            return View("New");
        }

        [HttpPost("chefs/create")]
        public IActionResult Create(Chef chef)
        {
            if (!ModelState.IsValid) { return View("New"); }

            _db.Chefs.Add(chef);
            _db.SaveChanges();
            
            return RedirectToAction("All");
        }

        private ChefsAndDishesContext _db;
    }
}

Controllers/DishController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using ChefsAndDishes.Models;

namespace ChefsAndDishes.Controllers
{
    public class DishController : Controller
    {
        public DishController(ChefsAndDishesContext context) { _db = context; }

        [HttpGet("dishes")]
        public IActionResult All()
        {
            List<Dish> Dishes = _db.Dishes
                .Include(dish => dish.Creator)
                .OrderBy(dish => dish.CreatedAt)
                .ToList();

            return View("All", Dishes);
        }
        
        [HttpGet("dishes/new")]
        public IActionResult New()
        {
            ViewBag.Chefs = _db.Chefs.ToList();
            return View("New");
        }

        [HttpPost("dishes/create")]
        public IActionResult Create(Dish newDish)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Chefs = _db.Chefs.ToList();
                return View("New");
            }

            Chef dbChef = _db.Chefs.FirstOrDefault(chef => chef.ChefId == newDish.ChefId);
            newDish.Creator = dbChef;

            _db.Dishes.Add(newDish);
            _db.SaveChanges();

            return RedirectToAction("All");
        }


        private ChefsAndDishesContext _db;
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ChefsAndDishes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ChefsAndDishes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <div>
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Chef" asp-action="All">Chefs</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Dish" asp-action="All">Dishes</a>
                                </li>
                            </ul>
                        </div>
                        <div>
                            <ul class="navbar-nav flex-grow-1">
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Chef" asp-action="New">Add A Chef</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Dish" asp-action="New">Add A Dish</a>
                                </li>
                            </ul>
                        </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ChefsAndDishes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>